on: [ push ]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            -   name: Check out project
                uses: actions/checkout@v2
            -   name: Capture build scan info
                id: hello
                uses: etiennestuder/build-scan-github-action@development
                with:
                    build-scan-path: './build-scan-info'
            # Use the output from the `hello` step
            -   name: Get the output time
                run: echo "The time was ${{ steps.hello.outputs.build-scan-url }}"
