name: "Other Integration Tests"
on: [push, workflow_dispatch]

jobs:
    some_job:
        runs-on: ubuntu-latest
        name: Another test
        steps:
            -   id: checkout
                name: Check out project
                uses: actions/checkout@v2
