name: "Integration Tests"
on: [ push ]

jobs:
    test_job:
        runs-on: ubuntu-latest
        name: Test
        steps:
            -   id: checkout
                name: Check out project
                uses: actions/checkout@v2
            -   id: build-scan
                name: Capture build scan info
                uses: etiennestuder/build-scan-github-action@development
                with:
                    build-scan-path: './build-scan-info'
            -   id: log
                name: Log captured build scan link
                run: echo "Build outcome is ${{ steps.build-scan.outputs.build-outcome }} and build scan is ${{ steps.build-scan.outputs.build-scan-url }}"
